### ISSUE TITLE
about 'BUFFER_PATH'

### ISSUE THREAD

**Issue by danelpeng** [Daffan/ros_jackal#1]
hello,what the BUFFER_PATH in the code means? how to set it?

**Comment by Daffan** [comment]
Hi, this repo saves the collected trajectories from each actor in a local buffer folder, also actors load the recent policy from this folder. I just updated the repo. Now by default, buffer folder is a folder named `local_buffer` in the current dictionary. You can specify a new folder as `export BUFFER_FOLDER=/PATH/TO/YOUR/BUFFER_FOLDER`. Let me know if you have more questions.

**Comment by danelpeng** [comment]
thank u very much!
