### ISSUE TITLE
in rl_algos/collector.py

### ISSUE THREAD

**Issue by danelpeng** [Daffan/ros_jackal#2]
code in collector.py (line 58、59、68），should not "obs = obs_new"(line 59) be placed after "self.buffer.add"(line 68)? Otherwise, buffer.add(obs_new, act, obs_new, rew, done, world, collision_reward), not  buffer.add(obs, act, obs_new, rew, done, world, collision_reward)

**Comment by Daffan** [comment]
Hi yes, you are right. Thanks for pointing this out. This local collector probably has not been tested, because it is very slow to run with only one ROS process locally. I usually just parallelize it using containers. I will update it now.

**Comment by Daffan** [comment]
If you want to try container. In the fourth step of the installation instruction, the anonymized singularity cloud account [XXX] is [zifanxu], you can try to pull a Singularity image following that instruction.

**Comment by danelpeng** [comment]
thank u.
